fix: encodage des commentaires
mission-apprentissage/tjp-pilotage pull request #454
Opened 2024-10-02 07:31 UTC by gBusato

Encodage des champs commentaires qui pourraient être rejetés par le WAF

2024-10-02 09:52 UTC, FaXaq approved these changes

2024-10-03 08:12 UTC, LucasDetre requested changes

2024-10-03 08:12 UTC, LucasDetre commented on server/src/modules/demandes/usecases/submitDemande/submitDemande.schema.ts
> +      motif: z
Pas nécessaire ici, la liste des motifs possibles est figée et controlée côté front (d'ailleurs on devrait peut-être utiliser une enum)

2024-10-03 08:12 UTC, LucasDetre commented on server/src/modules/demandes/usecases/submitDemande/submitDemande.schema.ts
> +      motifRefus: z
même chose

2024-10-03 08:12 UTC, LucasDetre commented on server/src/modules/intentions/usecases/submitIntention/submitIntention.schema.ts
> +      motif: z
même chose

2024-10-03 08:12 UTC, LucasDetre commented on server/src/modules/intentions/usecases/submitIntention/submitIntention.schema.ts
> +      motifRefus: z
même chose

2024-10-03 08:12 UTC, LucasDetre commented on ui/app/(wrapped)/intentions/perdir/saisie/intentionForm/IntentionForm.tsx
> +                  motif: values.motif?.map(
même chose, pas nécessaire du coup

2024-10-03 08:12 UTC, LucasDetre commented on ui/app/(wrapped)/intentions/perdir/saisie/intentionForm/IntentionForm.tsx
> +                  motifRefus: values.motifRefus?.map(
même chose

2024-10-03 08:12 UTC, LucasDetre commented on ui/app/(wrapped)/intentions/saisie/intentionForm/IntentionForm.tsx
> +                  motif: values.motif?.map(
même chose

2024-10-03 08:12 UTC, LucasDetre commented on ui/app/(wrapped)/intentions/saisie/intentionForm/IntentionForm.tsx
> +                  motifRefus: values.motifRefus?.map(
même chose

2024-10-03 08:12 UTC, LucasDetre commented on ui/app/(wrapped)/intentions/saisie/intentionForm/IntentionForm.tsx
> +                                    motif: values.motif?.map(
même chose

2024-10-03 08:12 UTC, LucasDetre commented on ui/app/(wrapped)/intentions/saisie/intentionForm/IntentionForm.tsx
> +                                    motifRefus: values.motifRefus?.map(
même chose

2024-10-23 10:05 UTC, merged