Pilotage de la reforme
mission-apprentissage/tjp-pilotage pull request #64
Opened 2023-08-22 09:19 UTC by LucasDetre

2023-08-23 15:55 UTC, flodlc reviewed
Je continue la review demain

2023-08-23 15:55 UTC, flodlc commented on server/src/modules/data/queries/getPilotageReformeStats/getPilotageReformeStats.query.ts
> +    .selectFrom("formationEtablissement")
Je vois pas à quoi sert la requête qui entoure `selectStatsEffectif`, j'ai essayé d'utiliser la sous-requête directement et j'obtient les mêmes résultats.
Est-ce que c'est pour jouer plusieurs requetes en une ?

2023-08-23 15:55 UTC, flodlc commented on server/src/modules/data/queries/getPilotageReformeStats/getPilotageReformeStats.query.ts
> +  const regions = await filtersBase
ici pas besoin du await qui est fait plus bas et permet de paralléliser les requetes.
Idem pour diplomes

2023-08-23 15:55 UTC, flodlc commented on server/src/modules/data/routes/pilotageReforme.routes.ts
> +//@ts-ignore
je crois que lui n'est plus nécessaire

2023-08-23 15:55 UTC, flodlc commented on shared/PILOTAGE_REFORME_STATS_REGIONS_COLUMNS.ts
Dans le cas de la console j'avais mis ici les colonnes pour être sur que l'export csv depuis le serveur avait les mêmes colonnes. Dans ce cas si pas d'export ce serait pas genant de nommer les colonnes directement là où elles sont utilisées. Comme tu préfères !

2023-08-23 15:55 UTC, flodlc commented on ui/app/(wrapped)/pilotage-reforme/stats/FiltersSection.tsx
> +                </option>
Le composant Select de chakra prend un placeholder en prop et permet de pas avoir besoin de faire ça

2023-08-24 07:23 UTC, LucasDetre commented on server/src/modules/data/queries/getPilotageReformeStats/getPilotageReformeStats.query.ts
> +    .selectFrom("formationEtablissement")
Oui, c'est histoire de factoriser l'usage de la requête et pouvoir l'utiliser dans des contextes d'année et de filtrage géographique différents

2023-08-28 12:43 UTC, flodlc requested changes

2023-08-28 12:43 UTC, flodlc commented on ui/app/(wrapped)/pilotage-reforme/page.tsx
> +    },
Une suggestion qui est pas moins lisible et rend le fichier plus concis selon moi, je te laisse choisir si tu préfères.
```suggestion
    queryFn: api.getPilotageReformeStatsRegions({         
        ...order,
        ...filters,
      }).call,
```

2023-08-28 12:43 UTC, flodlc commented on ui/app/(wrapped)/pilotage-reforme/page.tsx
> +    <>
Fragment inutile

2023-08-28 12:43 UTC, flodlc commented on ui/app/(wrapped)/pilotage-reforme/stats/VueRegionAcademieSection.tsx
> +          //@ts-ignore
Pas sûr que ce soit utile. Si ça l'est ignore mon message :)

2023-08-28 12:43 UTC, flodlc commented on ui/app/(wrapped)/pilotage-reforme/types.ts
> +>;
Et pareil en dessous 

```suggestion
export type PilotageReformeStats = ApiType<typeof api.getPilotageReformeStats>;
```

2023-08-28 12:59 UTC, LucasDetre commented on ui/app/(wrapped)/pilotage-reforme/page.tsx
> +    },
Ça serait pas plutôt 

```
queryFn: api.getPilotageReformeStats({
      query: {
        ...filters,
      },
    }).call
```
?

2023-08-29 10:03 UTC, flodlc approved these changes

2023-08-29 12:14 UTC, merged